os: Visual Studio 2015

clone_folder: c:/projects/units

branches:
  except:
    - gh-pages
    - documentation

platform:
  - x64

configuration:
  - Debug
  - Release

image:
- Visual Studio 2013
- Visual Studio 2015
- Visual Studio 2017

build_script:
  - md build
  - cd build
  - cmake -Wno-dev ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - cmd: ctest -VV -C %CONFIGURATION%
